{% extends 'layouts/main.swig' %}
{% block css %}
{% endblock %}
{% block js %}
{% endblock %}
{% block content %}
<ol class="breadcrumb">
    <li><a href="index.html"><i class="fa fa-home"></i></a></li>
    <li class="active">Замовлення</li>
</ol>
<div class="content container-fluid">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-lg-2">
            <div class="decor-default">

            </div>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-2">
            <div class="decor-default">

            </div>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-2">
            <div class="decor-default">

            </div>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-2">
            <div class="decor-default">

            </div>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-2">
            <div class="decor-default">

            </div>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-2">
            <div class="decor-default">

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-md-3">
            <div class="decor-default">

            </div>
        </div>
        <div class="col-sm-6 col-md-3">
            <div class="decor-default">

            </div>
        </div>
        <div class="col-sm-6 col-md-3">
            <div class="decor-default">

            </div>
        </div>
        <div class="col-sm-6 col-md-3">
            <div class="decor-default">

            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-sm-12 col-md-4">
            <div class="decor-default">

            </div>
        </div>
        <div class="col-sm-12 col-md-4">
            <div class="decor-default">

            </div>
        </div>
        <div class="col-sm-12 col-md-4">
            <div class="decor-default">

            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="decor-default">

            </div>
        </div>
        <div class="col-sm-6">
            <div class="decor-default">

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="decor-default">

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="decor-default">

            </div>
        </div>
    </div>
</div>
{% endblock %}