{% extends 'layouts/main.swig' %}
{% block css %}
{% endblock %}
{% block js %}
{% endblock %}
{% block content %}
<ol class="breadcrumb">
    <li><a href="index.html"><i class="fa fa-home"></i></a></li>
    <li class="active">Dashboard</li>
</ol>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-lg-2">
            <div class="decor-default">

            </div>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-2">
            <div class="decor-default">

            </div>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-2">
            <div class="decor-default">

            </div>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-2">
            <div class="decor-default">

            </div>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-2">
            <div class="decor-default">

            </div>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-2">
            <div class="decor-default">

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-md-3">
            <div class="decor-default">

            </div>
        </div>
        <div class="col-sm-6 col-md-3">
            <div class="decor-default">

            </div>
        </div>
        <div class="col-sm-6 col-md-3">
            <div class="decor-default">

            </div>
        </div>
        <div class="col-sm-6 col-md-3">
            <div class="decor-default">

            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-sm-12 col-md-4">
            <div class="decor-default">

            </div>
        </div>
        <div class="col-sm-12 col-md-4">
            <div class="decor-default">

            </div>
        </div>
        <div class="col-sm-12 col-md-4">
            <div class="decor-default">

            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="decor-default">

            </div>
        </div>
        <div class="col-sm-6">
            <div class="decor-default">
                Задача организации, в особенности же рамки и место обучения кадров в значительной степени обуславливает создание системы обучения кадров, соответствует насущным потребностям. Товарищи! укрепление и развитие структуры обеспечивает широкому кругу (специалистов) участие в формировании модели развития. Не следует, однако забывать, что консультация с широким активом способствует подготовки и реализации модели развития. Не следует, однако забывать, что начало повседневной работы по формированию позиции в значительной степени обуславливает создание дальнейших направлений развития. Таким образом начало повседневной работы по формированию позиции играет важную роль в формировании направлений прогрессивного развития.
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="decor-default">

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="decor-default">

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="decor-default">

            </div>
        </div>
    </div>
</div>
{% endblock %}